display_set_gui_size(320,240);
surface_resize(application_surface, 640, 480);
room_set_height(room, 240);
room_set_height(room, 320);

TE_Init();

NSP_initialize();

var txtid = TE_create();

//TE_add_line(txtid, "%MACRO[_TestInfiniteLoop,YOU DEVIOUS MANIGANCER!!!]%");
//TE_add_line(txtid, "%MATH[APPLE,=,0]%%NEWLINE%");
//TE_add_line(txtid, "%MACRO[_MacroReccursive,APPLE]%");
//TE_add_line(txtid, "We're at %VARIABLE[APPLE]% apples! :D");
/*TE_add_line(txtid, "%MATH[MACROCOUNT,=,0]%%NEWLINE%");
TE_add_line(txtid, "%LOOP%");
TE_add_line(txtid, "%INSTANT%Number of loops = %VARIABLE[MACROCOUNT]%");
TE_add_line(txtid, "%MACRO[_MacroTestA]%");
TE_add_line(txtid, "%MACRO[_MacroTestC]%");
TE_add_line(txtid, "%MACRO[_MacroTestB]%");
TE_add_line(txtid, "%MACRO[_MacroTestC]%");
TE_add_line(txtid, "%MACRO[_MacroTestB]%");
TE_add_line(txtid, "%MACRO[_MacroTestA]%");
TE_add_line(txtid, "%MATH[MACROCOUNT,+=,1]%%NEWLINE%");
TE_add_line(txtid, "%LOOPEND%");*/
//TE_add_line(txtid, "%GOTO[MACRO]%");
//TE_add_line(txtid, "%MACRO[_TestCondition]%");
//TE_add_line(txtid, "ye%CHOICE[&CHOICE[nyet,nyet]&ye,ye]%");
TE_add_line(txtid, "%FACE[sTE_Facetest,4]%Hi!%WAIT[20]%%FACE[sTE_Facetest,4]%This is the textbox engine\nby Quaker Oats :)");
TE_add_line(txtid, "%FACE[sTE_Facetest,1]%It is quite barebone right now%WAIT[10]%%FACE[sTE_Facetest,0]%\nbut with time it should become\ngood enough for game use");
//TE_add_line(txtid, "%MATH[TEST,=,25]%%GOTO[1234]%.");
TE_add_line(txtid, "Select section of demo!%CHOICE[&COLOR[c_red]&Pause,&COLOR[c_yellow]&Math,&COLOR[0,255,255]&Condition,&COLOR[c_black]&Macro]%");
TE_add_line(txtid, "%IF[TE_CHOICE,==,0]% %GOTO[PAUSE]%");
TE_add_line(txtid, "%IF[TE_CHOICE,==,1]% %GOTO[MATH]%");
TE_add_line(txtid, "%IF[TE_CHOICE,==,2]% %GOTO[IF]%");
TE_add_line(txtid, "%IF[TE_CHOICE,==,3]% %GOTO[MACRO]%");
TE_add_line(txtid, "%FACE[sTE_Facetest,5]%...");
TE_add_line(txtid, "%TAG[PAUSE]%");
TE_add_line(txtid, "%FACE[sTE_Facetest,0]%Press SPACE to advance text%PAUSE%%FACE[sTE_Facetest,4]%\nYOU DID IT :D");
TE_add_line(txtid, "%FACE[sTE_Facetest,3]%.%WAIT[5]%.%WAIT[5]%.%WAIT[5]%uh %WAIT[20]%maybe, %WAIT[20]% I guess.");
TE_add_line(txtid, "%FACE[sTE_Facetest,2]%I shall now go to the \"cuck\" tag :I");
TE_add_line(txtid, "%GOTO[CUCK]%");
TE_add_line(txtid, "%TAG[NYET]%");
TE_add_line(txtid, "%FACE[sTE_Facetest,3]%FAILURE :(");
TE_add_line(txtid, "%FACE[sTE_Facetest,5]%There's a bug in the matrix and IT'S ALL FUCKING SHIT");
TE_add_line(txtid, "%FACE[sTE_Facetest,1]%Disregard the success message, k thx");
TE_add_line(txtid, "%TAG[CUCK]%");
TE_add_line(txtid, "%FACE[sTE_Facetest,4]%SUCCESS :>");
TE_add_line(txtid, "%TAG[MATH]%");
TE_add_line(txtid, "%FACE[sTE_Facetest,1]%Now it's math time!");
TE_add_line(txtid, "%FACE[sTE_Facetest,0]%%MATH[TEST,=,50]%TEST variable is set to %VARIABLE[TEST]%.");
TE_add_line(txtid, "%FACE[sTE_Facetest,1]%%VARIABLE[TEST]% + 15 %MATH[TEST,+=,15]% == %VARIABLE[TEST]%.");
TE_add_line(txtid, "%FACE[sTE_Facetest,2]%%VARIABLE[TEST]% - 20 %MATH[TEST,-=,20]% == %VARIABLE[TEST]%.");
TE_add_line(txtid, "%TAG[1234]%");
TE_add_line(txtid, "%FACE[sTE_Facetest,3]%(%VARIABLE[TEST]% / 3) + 5 %MATH[TEST,/=,3]%%MATH[TEST,+=,5]%==%VARIABLE[TEST]%.");
TE_add_line(txtid, "%FACE[sTE_Facetest,4]%%VARIABLE[TEST]% * %VARIABLE[TEST]% %MATH[TEST,*=,VAR.TEST]%== %VARIABLE[TEST]%.");
TE_add_line(txtid, "%FACE[sTE_Facetest,5]%%VARIABLE[TEST]% mod 16 %MATH[TEST,MOD,16]%== %VARIABLE[TEST]%.");
TE_add_line(txtid, "%FACE[sTE_Facetest,2]%TEST is now %VARIABLE[TEST]%.%WAIT[30]%%PAUSE%\nAren't maths so.%WAIT[5]%.%WAIT[5]%. %WAIT[20]%%FACE[sTE_Facetest,1]%MAGICAL?!?!?!?");
TE_add_line(txtid, "%TAG[IF]%");
TE_add_line(txtid, "%FACE[sTE_Facetest,0]%It is now the most important question in the multiverse %MATH[TEST,=,45]");
TE_add_line(txtid, "%FACE[sTE_Facetest,1]%Is TEST (%VARIABLE[TEST]%) worth 50?");
TE_add_line(txtid, "%IF[TEST,!=,50]%%NEWLINE%");
TE_add_line(txtid, "%{%");
TE_add_line(txtid, "%FACE[sTE_Facetest,3]%FAILURE <:O%PAUSE%\n%FACE[sTE_Facetest,1]%Is the condition alright?%WAIT[20]%\n%FACE[sTE_Facetest,5]%Of course you dumb shit!%PAUSE%\nGO TO HELL!!!");
TE_add_line(txtid, "%}%");
TE_add_line(txtid, "%ELSE%");
TE_add_line(txtid, "%{%");
TE_add_line(txtid, "%FACE[sTE_Facetest,4]%SUCCESS!%PAUSE%\nIf there is a error message, it means that we cucked up :(");
TE_add_line(txtid, "%}%");
TE_add_line(txtid, "%TAG[MACRO]%");
TE_add_line(txtid, "%FACE[sTE_Facetest,4]%Hey let's test macros!");
TE_add_line(txtid, "%FACE[sTE_Facetest,1]%Let's run macro \"_Test\"");
TE_add_line(txtid, "%MACRO[_TEST,Happy]%");
TE_add_line(txtid, "Now testing \"ASSTITCUCK\"");
TE_add_line(txtid, "%MACRO[ASSTITCUCK]%");
TE_add_line(txtid, "Now it's TEST again");
TE_add_line(txtid, "%MACRO[_TEST]%");
TE_add_line(txtid, "Yep I'm finished :)");
TE_add_line(txtid, "%FACE[sTE_Facetest,2]%k bye");
TE_add_line(txtid, "%END%");