display_set_gui_size(320,240);
surface_resize(application_surface, 640, 480);
room_set_height(room, 240);
room_set_height(room, 320);

var txtid = TE_create();


TE_add_line(txtid, "%NEWLINE%");
TE_add_line(txtid, "%MACRO[_InventoryTest]%");
/*TE_add_line(txtid, "%LOOP%");
TE_add_line(txtid, "%INSTANT%105=%VARIABLE[VAR.NPC105.test]%, 1010=%VARIABLE[VAR.NPC1010.test]%, 248=%VARIABLE[VAR.NPC248.test]%%WAIT[2]%%NEWLINE%");
TE_add_line(txtid, "%MATH[NPC105.test,+=,3]%%NEWLINE%");
TE_add_line(txtid, "%MATH[NPC1010.test,+=,2]%%NEWLINE%");
TE_add_line(txtid, "%MATH[NPC248.test,+=,1]%%NEWLINE%");
TE_add_line(txtid, "%LOOPBREAK%");
TE_add_line(txtid, "%LOOPEND%");*/
//TE_add_line(txtid, "%MACRO[_TestInfiniteLoop,YOU DEVIOUS MANIGANCER!!!]%");
//TE_add_line(txtid, "%MATH[APPLE,=,0]%%NEWLINE%");
//TE_add_line(txtid, "%MACRO[_MacroReccursive,APPLE]%");
//TE_add_line(txtid, "We're at %VARIABLE[VAR.APPLE]% apples! :D");
/*TE_add_line(txtid, "%MATH[MACROCOUNT,=,0]%%NEWLINE%");
TE_add_line(txtid, "%LOOP%");
TE_add_line(txtid, "%INSTANT%Number of loops = %VARIABLE[VAR.MACROCOUNT]%");
TE_add_line(txtid, "%MACRO[_MacroTestA]%");
TE_add_line(txtid, "%MACRO[_MacroTestC]%");
TE_add_line(txtid, "%MACRO[_MacroTestB]%");
TE_add_line(txtid, "%MACRO[_MacroTestC]%");
TE_add_line(txtid, "%MACRO[_MacroTestB]%");
TE_add_line(txtid, "%MACRO[_MacroTestA]%");
TE_add_line(txtid, "%MATH[MACROCOUNT,+=,1]%%NEWLINE%");
TE_add_line(txtid, "%LOOPEND%");*/
//TE_add_line(txtid, "%GOTO[MACRO]%");
//TE_add_line(txtid, "%MACRO[_TestCondition]%");
//TE_add_line(txtid, "ye%CHOICE[&CHOICE[nyet,nyet]&ye,ye]%");
//TE_add_line(txtid, "%GOTO[CHARPOS]%");
TE_add_line(txtid, "%FACE[sTE_Facetest,4]%Hi!%WAIT[20]%%FACE[sTE_Facetest,4]%This is the textbox engine\nby Quaker Oats :)");
TE_add_line(txtid, "%FACE[sTE_Facetest,1]%It is quite barebone right now%WAIT[10]%%FACE[sTE_Facetest,0]%\nbut with time it should become\ngood enough for game use");
//TE_add_line(txtid, "%MATH[TEST,=,25]%%GOTO[1234]%.");
TE_add_line(txtid, "Select section of demo!%CHOICE[&COLOR[c_red]&Pause,&COLOR[c_white]&Music,&COLOR[c_yellow]&Math,&COLOR[0,255,255]&Condition,&COLOR[c_black]&Macro,&COLOR[255,255,64]&Charpos,Number Input]%");
TE_add_line(txtid, "%IF[VAR.TE_CHOICE,==,0]% %GOTO[PAUSE]%");
TE_add_line(txtid, "%IF[VAR.TE_CHOICE,==,1]% %GOTO[MUSIC]%");
TE_add_line(txtid, "%IF[VAR.TE_CHOICE,==,2]% %GOTO[MATH]%");
TE_add_line(txtid, "%IF[VAR.TE_CHOICE,==,3]% %GOTO[IF]%");
TE_add_line(txtid, "%IF[VAR.TE_CHOICE,==,4]% %GOTO[MACRO]%");
TE_add_line(txtid, "%IF[VAR.TE_CHOICE,==,5]% %GOTO[CHARPOS]%");
TE_add_line(txtid, "%IF[VAR.TE_CHOICE,==,6]% %GOTO[INPUTNUM]%");
TE_add_line(txtid, "%FACE[sTE_Facetest,5]%...");
TE_add_line(txtid, "%TAG[PAUSE]%");
TE_add_line(txtid, "%FACE[sTE_Facetest,0]%Press SPACE to advance text%PAUSE%%FACE[sTE_Facetest,4]%\nYOU DID IT :D");
TE_add_line(txtid, "%FACE[sTE_Facetest,3]%.%WAIT[5]%.%WAIT[5]%.%WAIT[5]%uh %WAIT[20]%maybe, %WAIT[20]% I guess.");
TE_add_line(txtid, "%FACE[sTE_Facetest,2]%I shall now go to the \"cuck\" tag :I");
TE_add_line(txtid, "%GOTO[CUCK]%");
TE_add_line(txtid, "%TAG[NYET]%");
TE_add_line(txtid, "%FACE[sTE_Facetest,3]%FAILURE :(");
TE_add_line(txtid, "%FACE[sTE_Facetest,5]%There's a bug in the matrix and IT'S ALL FUCKING SHIT");
TE_add_line(txtid, "%FACE[sTE_Facetest,1]%Disregard the success message, k thx");
TE_add_line(txtid, "%TAG[CUCK]%");
TE_add_line(txtid, "%FACE[sTE_Facetest,4]%SUCCESS :>");
TE_add_line(txtid, "%TAG[MUSIC]%");
TE_add_line(txtid, "What about some music?%WAIT[20]%\nWould you like some?%CHOICE[FUCK YEAH LET'S ROCK!!!,I hate music.]%");
TE_add_line(txtid, "%IF[VAR.TE_CHOICE,==,0]%%GOTO[MUSIC_OK]%");
TE_add_line(txtid, "Oh...");
TE_add_line(txtid, "%GOTO[MATH]%");
TE_add_line(txtid, "%TAG[MUSIC_OK]%");
TE_add_line(txtid, "What kind of music do you want?%CHOICE[canyon.mid,DRAGON FORCE,Solstice,Bad Company by Bad Company]%");
TE_add_line(txtid, "%IF[VAR.TE_CHOICE,==,0]%%ME_PLAYMUSIC[_test,5,1.5]%HAHA!!! EARRAPE%PAUSE%%GOTO[MUSIC_END]%");
TE_add_line(txtid, "%IF[VAR.TE_CHOICE,==,1]%%ME_PLAYMUSIC[_ttfaf]%YEAH BABY, THAT'S THE SPIRIT!!!%PAUSE%%GOTO[MUSIC_END]%");
TE_add_line(txtid, "%IF[VAR.TE_CHOICE,==,2]%%ME_PLAYMUSIC[_solstice]%Watch your temper cuz it's time for\nSOLSTICE!!!!!!!1!! >:)%PAUSE%%GOTO[MUSIC_END]%");
TE_add_line(txtid, "%IF[VAR.TE_CHOICE,==,3]%%ME_PLAYMUSIC[_badcompany]%VERY COOL!!!%PAUSE%%GOTO[MUSIC_END]%");
TE_add_line(txtid, "%TAG[MUSIC_END]%");
TE_add_line(txtid, "Another choice?%CHOICE[Ye,Nah]%");
TE_add_line(txtid, "%IF[VAR.TE_CHOICE,==,0]%%GOTO[MUSIC_OK]%");
TE_add_line(txtid, "%TAG[MATH]%");
TE_add_line(txtid, "%FACE[sTE_Facetest,1]%Now it's math time!");
TE_add_line(txtid, "%FACE[sTE_Facetest,0]%%MATH[VAR.TEST,=,50]%TEST variable is set to %VARIABLE[VAR.TEST]%.");
TE_add_line(txtid, "%FACE[sTE_Facetest,1]%%VARIABLE[VAR.TEST]% + 15 %MATH[VAR.TEST,+=,15]% == %VARIABLE[VAR.TEST]%.");
TE_add_line(txtid, "%FACE[sTE_Facetest,2]%%VARIABLE[VAR.TEST]% - 20 %MATH[VAR.TEST,-=,20]% == %VARIABLE[VAR.TEST]%.");
TE_add_line(txtid, "%TAG[1234]%");
TE_add_line(txtid, "%FACE[sTE_Facetest,3]%(%VARIABLE[VAR.TEST]% / 3) + 5 %MATH[VAR.TEST,/=,3]%%MATH[VAR.TEST,+=,5]%==%VARIABLE[VAR.TEST]%.");
TE_add_line(txtid, "%FACE[sTE_Facetest,4]%%VARIABLE[VAR.TEST]% * %VARIABLE[VAR.TEST]% %MATH[VAR.TEST,*=, 0 + VAR.TEST]%== %VARIABLE[VAR.TEST]%.");
TE_add_line(txtid, "%FACE[sTE_Facetest,5]%%VARIABLE[VAR.TEST]% mod 16 %MATH[VAR.TEST,MOD,16]%== %VARIABLE[VAR.TEST]%.");
TE_add_line(txtid, "%FACE[sTE_Facetest,2]%TEST is now %VARIABLE[VAR.TEST]%.%WAIT[30]%%PAUSE%\nAren't maths so.%WAIT[5]%.%WAIT[5]%. %WAIT[20]%%FACE[sTE_Facetest,1]%MAGICAL?!?!?!?");
TE_add_line(txtid, "%TAG[IF]%");
TE_add_line(txtid, "%FACE[sTE_Facetest,0]%It is now the most important question in the multiverse %MATH[TEST,=,45]");
TE_add_line(txtid, "%FACE[sTE_Facetest,1]%Is TEST (%VARIABLE[VAR.TEST]%) worth 50?");
TE_add_line(txtid, "%IF[VAR.TEST,!=,50]%%NEWLINE%");
TE_add_line(txtid, "%{%");
TE_add_line(txtid, "%FACE[sTE_Facetest,3]%FAILURE <:O%PAUSE%\n%FACE[sTE_Facetest,1]%Is the condition alright?%WAIT[20]%\n%FACE[sTE_Facetest,5]%Of course you dumb shit!%PAUSE%\nGO TO HELL!!!");
TE_add_line(txtid, "%}%");
TE_add_line(txtid, "%ELSE%");
TE_add_line(txtid, "%{%");
TE_add_line(txtid, "%FACE[sTE_Facetest,4]%SUCCESS!%PAUSE%\nIf there is a error message, it means that we cucked up :(");
TE_add_line(txtid, "%}%");
TE_add_line(txtid, "%TAG[MACRO]%");
TE_add_line(txtid, "%FACE[sTE_Facetest,4]%Hey let's test macros!");
TE_add_line(txtid, "%FACE[sTE_Facetest,1]%Let's run macro \"_Test\"");
TE_add_line(txtid, "%MACRO[_TEST,Happy]%");
TE_add_line(txtid, "Now testing \"ASSTITCUCK\"");
TE_add_line(txtid, "%MACRO[ASSTITCUCK]%");
TE_add_line(txtid, "Now it's TEST again");
TE_add_line(txtid, "%MACRO[_TEST]%");
TE_add_line(txtid, "%FACE[sTE_Facetest,0]%Yep I'm finished :)");
TE_add_line(txtid, "%TAG[CHARPOS]%");
TE_add_line(txtid, "%FACE[sTE_Facetest,1]%Let's try something new!");
TE_add_line(txtid, "%FACE[blablabla,2]%%CHARW[8, 240]%Dragon Sword\nMagic Wand\nSuperb Leprechaun\nWith <3%CHARW[248,320]%%CHARHALIGN[fa_right]%%CHARPOS[320,8]%%LONGCHAR[30$]% \n%LONGCHAR[50$]% \n%LONGCHAR[150$]% \n%LONGCHAR[FREE]%");
TE_add_line(txtid, "Hope it works :)");
TE_add_line(txtid, "%INSTANT%77777777777777777777777777777777777777777777777777777777777777777777777777777777");
TE_add_line(txtid, "%CHARW[0,160]%%INSTANT%77777777777777777777777777777777777777777777777777777777777777777777777777777777");
TE_add_line(txtid, "%CHARW[160,320]%%INSTANT%77777777777777777777777777777777777777777777777777777777777777777777777777777777");
TE_add_line(txtid, "%CHARW[80,240]%%INSTANT%77777777777777777777777777777777777777777777777777777777777777777777777777777777");
TE_add_line(txtid, "%TAG[INPUTNUM]%");
TE_add_line(txtid, "Can I ask you a question?%PAUSE%\nWhat year is it?%ASKREAL[4,2000]%");
TE_add_line(txtid, "%IF[VAR.TE_ASKREAL,==,2018]%Ah, %WAIT[10]%what a relief!%PAUSE%%GOTO[INPUTNUM_END]%");
TE_add_line(txtid, "%IF[VAR.TE_ASKREAL,==,2084]%SHIT THE ROBOT INVASION\nIS COMING!!!!!!%PAUSE%%GOTO[INPUTNUM_END]%");
TE_add_line(txtid, "%IF[VAR.TE_ASKREAL,==,1984]%Big Brother is watching ya!%PAUSE%%GOTO[INPUTNUM_END]%");
TE_add_line(txtid, "%IF[VAR.TE_ASKREAL,==,2000]%%LONGCHAR[BUG]%%WAIT[5]%%LONGCHAR[BUG]%%WAIT[5]%%LONGCHAR[BUG]%%WAIT[5]%%LONGCHAR[BUG]%%WAIT[5]%%LONGCHAR[BUG]%%WAIT[5]%%LONGCHAR[BUG]%%WAIT[5]%%LONGCHAR[BUG]%%WAIT[5]%%LONGCHAR[BUG]%%WAIT[5]%%LONGCHAR[BUG]%%WAIT[5]%%LONGCHAR[BUG]%%WAIT[5]%%LONGCHAR[BUG]%%WAIT[5]%%LONGCHAR[BUG]%%WAIT[5]%%LONGCHAR[BUG]%%WAIT[5]%%LONGCHAR[BUG]%%WAIT[5]%%PAUSE%%GOTO[INPUTNUM_END]%");
TE_add_line(txtid, "%IF[VAR.TE_ASKREAL,==,9999]%Yep, %WAIT[10]%we're so far away!%PAUSE%%GOTO[INPUTNUM_END]%");
TE_add_line(txtid, "%IF[VAR.TE_ASKREAL,==,0]%ALL HAIL OUR LORD CHRIST!!!!%PAUSE%%GOTO[INPUTNUM_END]%");
TE_add_line(txtid, "%IF[VAR.TE_ASKREAL,>,2018]%Uh, %WAIT[10]%we're in the future now?%PAUSE%%GOTO[INPUTNUM_END]%");
TE_add_line(txtid, "%IF[VAR.TE_ASKREAL,<,2018]%Don't get stuck in the past.%PAUSE%%GOTO[INPUTNUM_END]%");
TE_add_line(txtid, "%TAG[INPUTNUM_END]%");
TE_add_line(txtid, "Dare to tell me again?%CHOICE[Suck a cock you wanker,I'm an indecisive boi]%");
TE_add_line(txtid, "%IF[VAR.TE_CHOICE,==,1]%%GOTO[INPUTNUM]%");
TE_add_line(txtid, "%FACE[sTE_Facetest,2]%k bye");
TE_add_line(txtid, "%END%");